spring:
  application:
    name: cors
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10001/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
server:
  port: 10004